import { expect, test } from '@playwright/test';
import path from 'node:path';
import { expectNoHorizontalOverflow, expectNoSeriousA11yIssues } from './helpers';

test('horizontal advice, persisted preparation progress, upload binding, save and missing-material guard', async ({ page }, testInfo) => {
  test.setTimeout(150_000);
  await page.goto('/projects/new');
  await page.getByLabel('视频想法').fill(`流程回归 ${Date.now()}：张雪820RR，简单图片展示。`);
  await page.getByRole('button', { name: '获取创意建议' }).click();
  await expect(page.getByRole('button', { name: '采用这个方向' })).toHaveCount(3);
  const projectId = page.url().split('/').at(-2);
  const cards = page.locator('.proposal-card');
  const boxes = await cards.evaluateAll(nodes => nodes.map(node => ({ x: node.getBoundingClientRect().x, y: node.getBoundingClientRect().y })));
  expect(new Set(boxes.map(box => Math.round(box.y))).size).toBe(1);
  expect(boxes[1].x).toBeGreaterThan(boxes[0].x);
  await expectNoHorizontalOverflow(page);
  await expectNoSeriousA11yIssues(page);
  await page.screenshot({ path: testInfo.outputPath('strategy-desktop.png'), fullPage: true });
  await page.setViewportSize({ width: 390, height: 844 });
  await expectNoHorizontalOverflow(page);
  const comparison = page.getByRole('region', { name: '叙事方向比较' });
  expect(await comparison.evaluate(node => node.scrollWidth > node.clientWidth)).toBe(true);
  await comparison.focus();
  await page.keyboard.press('ArrowRight');
  await page.screenshot({ path: testInfo.outputPath('strategy-mobile.png'), fullPage: true });
  await page.setViewportSize({ width: 1440, height: 900 });
  await page.getByRole('button', { name: '采用这个方向' }).first().click();
  let holdProgress = true;
  await page.route('**/storyboard-runs/latest', async route => {
    const response = await route.fetch();
    const data = await response.json();
    if (holdProgress && data.run) data.run = { ...data.run, status: 'running', phase: 'writing-script', storyboardVersionId: null };
    await route.fulfill({ response, json: data });
  });
  await page.getByRole('button', { name: '确认并生成脚本' }).click();
  const progress = page.getByRole('region', { name: '脚本生成进度' });
  await expect(progress).toBeVisible();
  await page.reload();
  await expect(progress).toBeVisible();
  await expect(progress.getByRole('status')).toHaveText('大模型正在生成脚本');
  holdProgress = false;
  await page.waitForURL('**/storyboard');
  await expect(page.getByRole('button', { name: '生成选项', exact: true })).toBeVisible();
  await page.unroute('**/storyboard-runs/latest');
  await page.getByRole('button', { name: '生成选项', exact: true }).click();
  await expect(page.getByRole('region', { name: '素材准备结果' })).toContainText('个镜头待处理');
  await expect(page).toHaveURL(/\/storyboard$/);
  const file = path.resolve(__dirname, '../public/images/motorcycle-studio.jpg');
  await page.locator('.media-upload input[type=file]').setInputFiles(file);
  await expect(page.getByRole('status').filter({ hasText: '素材已上传并绑定当前镜头' })).toBeVisible();
  await page.getByText('高级设置', { exact: true }).click();
  const selected = page.getByRole('combobox', { name: '镜头素材', exact: true });
  const id = await selected.inputValue();
  expect(id).toBeTruthy();
  await expect.poll(() => page.locator('.vertical-stage img').evaluate((img: HTMLImageElement) => img.complete && img.naturalWidth > 0)).toBe(true);
  await expect(page.getByText('有未保存修改', { exact: true }).first()).toBeVisible();
  await page.getByRole('button', { name: '保存分镜', exact: true }).click();
  await expect(page.getByRole('status').filter({ hasText: '分镜已保存' })).toBeVisible();
  await expect(page).toHaveURL(/\/storyboard$/);
  await page.reload();
  await page.getByText('高级设置', { exact: true }).click();
  await expect(selected).toHaveValue(id);
  await page.getByRole('button', { name: '自动准备素材' }).click();
  await expect(page.getByRole('region', { name: '素材准备结果' })).toContainText('素材已就绪');
  const state = await (await page.request.get(`/api/v1/projects/${projectId}/workspace`)).json();
  expect(state.generationReadiness.ready).toBe(true);
  await page.getByRole('button', { name: '准备并生成视频', exact: true }).click();
  await page.waitForURL('**/generation');
  await expect(page.getByRole('link', { name: '查看成片' })).toBeVisible({ timeout: 90_000 });
});

test('workspace read failure has an explicit recovery action', async ({ page }) => {
  const created = await page.request.post('/api/v1/projects', { data: { title: '恢复工作区测试', initialMessage: '车型展示' } });
  const project = await created.json();
  await page.route('**/workspace', route => route.fulfill({ status: 503, json: { detail: '暂时不可用' } }));
  await page.goto(`/projects/${project.id}/storyboard`);
  await expect(page.getByRole('alert').filter({ hasText: '工作区加载失败' })).toBeVisible();
  await page.unroute('**/workspace');
  await page.getByRole('button', { name: '重新载入', exact: true }).click();
  await expect(page.getByText('还没有可编辑的 Storyboard', { exact: true })).toBeVisible();
});
