import { expect, test } from "@playwright/test";
import { expectNoHorizontalOverflow, expectNoSeriousA11yIssues } from "./helpers";

test("video configuration persists without a paid probe", async ({ page }, testInfo) => {
  const suffix = Date.now();
  const name = `fal-config-${suffix}`;
  await page.goto("/admin/model-providers");
  await page.getByRole("button", { name: "添加平台" }).click();
  await page.getByLabel("平台 ID").fill(name);
  await page.getByLabel("显示名称").fill(name);
  await page.getByLabel("适配器").selectOption("fal-video");
  await page.getByLabel("Base URL").fill("https://queue.fal.run");
  await page.getByRole("button", { name: "创建平台" }).click();
  await expect(page.locator("strong").filter({ hasText: name })).toBeVisible();
  await page.getByRole("link", { name: "API Key" }).click();
  await page.getByLabel("模型平台").selectOption({ label: name });
  await page.getByLabel("凭据别名").fill(name);
  await page.getByLabel("API Key").fill("test-video-key-not-real-9944");
  await page.getByRole("button", { name: "加密保存" }).click();
  await expect(page.getByLabel("API Key")).toHaveValue("");
  await page.getByRole("link", { name: "模型部署" }).click();
  await page.getByLabel("部署名称").fill(name);
  await page.getByLabel("模型平台").selectOption({ label: name });
  await page.getByLabel("物理模型 ID").fill("fal-ai/kling-video/v2.1/standard/image-to-video");
  await page.getByLabel("调用凭据").selectOption({ label: `${name} · 9944` });
  await page.locator('input[name="capabilities"]').fill("image-to-video");
  await page.getByRole("button", { name: "创建部署" }).click();
  await expect(page.locator(".deployment-row").filter({ hasText: name })).toBeVisible();
  await page.getByRole("link", { name: "视频执行", exact: true }).click();
  await page.getByLabel("执行方式").selectOption("fal");
  await page.getByLabel("执行部署").selectOption({ label: name });
  const deploymentId = await page.getByLabel("执行部署").inputValue();
  await page.getByLabel("参考单价（USD / 秒）").fill("0.1");
  await page.getByLabel("单任务累计估算上限（USD）").fill("2");
  await page.getByLabel("启用付费视频调用").check();
  await page.getByRole("button", { name: "保存视频配置" }).click();
  await expect(page.getByText("配置已保存；尚未执行付费生成验证。")).toBeVisible();
  await page.reload();
  await expect(page.getByLabel("执行部署")).toHaveValue(deploymentId);
  await expect(page.getByLabel("启用付费视频调用")).toBeChecked();
  await expect(page.getByLabel("参考单价（USD / 秒）")).toHaveValue("0.1");
  await expect(page.getByText("当前环境禁止外部调用。")).toBeVisible();
  expect(await page.locator("body").textContent()).not.toContain("test-video-key-not-real");
  await expectNoHorizontalOverflow(page);
  await expectNoSeriousA11yIssues(page);
  await page.screenshot({ path: testInfo.outputPath("video-settings-desktop.png"), fullPage: true });
  await page.setViewportSize({ width: 390, height: 844 });
  await expectNoHorizontalOverflow(page);
  await page.screenshot({ path: testInfo.outputPath("video-settings-mobile.png"), fullPage: true });
  await page.setViewportSize({ width: 320, height: 740 });
  await expectNoHorizontalOverflow(page);
});
